### ISSUE TITLE
SportHD not working on FireTV anymore (Kodi 20 / 21)

### ISSUE THREAD

**Issue by engels0n** [bugatsinho/bugatsinho.github.io#148]
Hi,
the SportHD addon doesn't work anymore on the firetv stick 4k. 
It just shows "SportHD Error - Check Logs" with the red X ;)

Don't know to get a log out of that stick, but it seems that a "request"-module is missing....

Hope you can fix it :-*

**Comment by SonGokuSSJ** [comment]
Workaround is to download the Addon zip file directly and copy it to a folder accessable from Kodi. On my Fire TV Stick I use adblink to "push" the file to the Download folder known by Kodi. Latest version in the repo is v0.1.52. 

The zip files are located here: https://github.com/bugatsinho/bugatsinho.github.io/tree/master/_zips

The Repo itself still only shows an older version for download (0.1.41 instead of 0.1.52). So I guess the Repo itself needs to be fixed to show newer versions.

**Comment by engels0n** [comment]
@SonGokuSSJ 
I'll try and report ;)

thx in advance

**Comment by SonGokuSSJ** [comment]
Maybe it is also a bug / on purpose with Kodi Version 20.x. I just updated from Kodi v20.5 to v21.0 and now the repository let me download v0.1.52.

**Comment by engels0n** [comment]
And does the addon work? Could you try to open a stream ?

**Comment by SonGokuSSJ** [comment]
Yes, the addon worked. It has shown streams and I was able to watch them.

**Comment by agelosnm** [comment]
> Maybe it is also a bug / on purpose with Kodi Version 20.x. I just updated from Kodi v20.5 to v21.0 and now the repository let me download v0.1.52.

I have Kodi version 21.0 and plugin one 0.1.52 but I do face the issue (I'm on a PC)

**Comment by engels0n** [comment]
@agelosnm 

I think I found the solution.
Look at the dependencies of the sporthd addon.

For me it seems that the request dependency was not installed anymore.

After installing (just click on it and press install) the plugin worked again!

@bugatsinho looks like there is a dependency issue with the newest repo version.

**Comment by bugatsinho** [comment]
By uninstall and reinstall add-on problem solved! Thank you

**Comment by engels0n** [comment]
Ok 👌 
Thread closed
