### ISSUE TITLE
Release BB search function not working

### ISSUE THREAD

**Issue by sb2780** [bugatsinho/bugatsinho.github.io#55]
Have tried switching between domains and still not working. Running version 1.9.0. Is this a known issue from the cloudscraper2 updates?

**Comment by DjDiabolik** [comment]
Exactly... apparently the address it's search.rlsbb.ru but right now it's use Cloudflare.

Also on my setup apparently the search it's not anymore works and appears somethings like an "hidden" notification on my tv.

**Comment by bugatsinho** [comment]
it also uses the new cloudflare challenge that cloudscraper can't bypass. sorry guy nothing to do about it

**Comment by DjDiabolik** [comment]
the thing that seems strange to me it's because it's also add this cloudflare "protection" only for search domain and not for all main site.....

however there should be a way to bypass cloudflare checks..... and maybe I even know someone who could tell us how....

**Comment by bugatsinho** [comment]
because search function has the most hits as all the Exodus forks addons uses search function

**Comment by DjDiabolik** [comment]
> 
> 
> because search function has the most hits as all the Exodus forks addons uses search function

I hadn't thought about this solution.....

**Comment by DjDiabolik** [comment]
> 
> 
> the thing that seems strange to me it's because it's also add this cloudflare "protection" only for search domain and not for all main site.....
> 
> however there should be a way to bypass cloudflare checks..... and maybe I even know someone who could tell us how....

About his my reply....
I have speak about cloudflare protection with my acquaintance that I mentioned here.
I have pass to him the search domain on rlsbb site and he also confirmed to me that the current version of cloudflare used at today it is not yet bypassable in any way.
He told me that in theory you should open a browser session to the user....and then take cookies of this session and use after on kodi addons....... it is not a solution to be considered according to him.

Too bad because without the "search" the use of addons is badly castrated :(

**Comment by fedevx** [comment]
rlsbb.ru uses CloudFlare version 2 challenge which is not going to be supported (for free at least) in cloudscraper. You can see [this commit](https://github.com/VeNoMouS/cloudscraper/commit/44aa5ce513d99a7445143ffe30b99180aac86e88).

The easier alternative to get search back to work would seem to be change the domain used for searching in "search.py". Rather than "search.rlsbb.ru" use "search.proxybb.com" which is (at least currently) not using CloudFlare.

**Comment by DjDiabolik** [comment]
Oh interesting... it's fixed right now ? We can back to use search ? If yes thanks 👍

**Comment by DjDiabolik** [comment]
Cloudflare as been also added/installed/or somethings similar on proxybb.com.

Search feature it's down yet :(

**Comment by DjDiabolik** [comment]
@bugatsinho ^^

**Comment by bugatsinho** [comment]
Yes thank you we all know that days now!

**Comment by fedevx** [comment]
so here is a bad work-around. The guys at proxybb.com have an MX record pointing to their real IP address which happens to be the same hosting their web service (likely they will correct it soon, if they read this). So you could very well use that information to get this working again. At least on some devices, you can set your router/hosts/resolv/dnsmasq to always resolve proxybb.com to the real IP address (there is no HTTPs, so HTTP only). I do realize this is not something everyone could use.

On a side note, having the search URI in search.py as a variable (better if read from settings) would be great, having hard-coded values is a pain.

A more appropriate fix (though perhaps not suitable for all platforms) would be to use selenium, running headless, to fetch and store the cookies and then set those when carrying out requests.

**Comment by bugatsinho** [comment]
> so here is a bad work-around. The guys at proxybb.com have an MX record pointing to their real IP address which happens to be the same hosting their web service (likely they will correct it soon, if they read this). So you could very well use that information to get this working again. At least on some devices, you can set your router/hosts/resolv/dnsmasq to always resolve proxybb.com to the real IP address (there is no HTTPs, so HTTP only). I do realize this is not something everyone could use.
> 
> On a side note, having the search URI in search.py as a variable (better if read from settings) would be great, having hard-coded values is a pain.
> 
> A more appropriate fix (though perhaps not suitable for all platforms) would be to use selenium, running headless, to fetch and store the cookies and then set those when carrying out requests.

SEARCH URL is only one for the three domains i have in the settings **search.rlssbb.ru** and lately the **search.proxybb** 
so for example if i do your fix the search doesnt work for the rlsbb.to neither for the unblock domain. WHEN search url isnt under cloudflare. Thank you
